lexik_jwt_authentication:
    secret_key: '%kernel.project_dir%/config/jwt/private.pem'
    public_key: '%kernel.project_dir%/config/jwt/public.pem
    pass_phrase: '769dfd18e9edc47b3e48b53e1b81002f24ad7ae3f55d96dc63122526a92add0d'
    token_ttl: 3600

    api_platform:
        check_path: /api/login_check
        username_path: email
        password_path: security.credentials.password