version: "3.8"
services:

  db:
    container_name: ozapay_postgres_container
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root      
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ozapay
    networks:
      - ozapay
      
  pgadmin:
    container_name: ozapay_pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    ports:
      - "5051:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@domain.com
      - PGADMIN_DEFAULT_PASSWORD=root
    depends_on: 
      - db
    networks:
      - ozapay
    #https://stackoverflow.com/questions/25540711/docker-postgres-pgadmin-local-connection
  back:
    build: build
    container_name: ozapay
    ports:
      - "94:80"
    volumes:
      - ./build/vhost.conf:/etc/apache2/sites-enabled/vhosts.conf
      - ./:/var/www
      - ./build/php.ini:/usr/local/etc/php/php.ini
    restart: always
    networks:
      - ozapay

###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB:-app}", "-U", "${POSTGRES_USER:-app}"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - database_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

networks:
    ozapay:

volumes:
    db:
    pgadmin:
    database_data:
