<?php

namespace App\Common\Constants\Response;

class ErrorsConstant
{
    //    ### Http Response
    public const INVALID_REQUEST = 'INVALID_REQUEST';
    public const INVALID_CREDENTIALS = 'INVALID_CREDENTIALS';
    public const NOT_FOUND = 'NOT_FOUND';
    public const VALIDATION_EXIST = 'VALIDATION_EXIST';
    public const MUST_BE_UNIQUE_VALUE = 'MUST_BE_UNIQUE_VALUE';
    public const CONSUMER_MUST_HAVE_PHONE = 'CONSUMER_MUST_HAVE_PHONE';
    public const PHONE_ALREADY_EXIST = 'PHONE_ALREADY_EXIST';
    public const EMAIL_ALREADY_EXIST = 'EMAIL_ALREADY_EXIST';
    public const USER_NOT_FOUND = 'USER_NOT_FOUND';

    ###LINKCY ERROR
    public const LINKCY_API_ERROR_CREATE_CONSUMER = 'LINKCY_API_ERROR_CREATE_CONSUMER';
    public const LINKCY_API_ERROR_CREATE_LEDGER = 'LINKCY_API_ERROR_CREATE_LEDGER';
    public const LINKCY_API_ERROR_CREATE_CARD_PROFILES = 'LINKCY_API_ERROR_CREATE_CARD_PROFILES';
    public const LINKCY_API_ERROR_CREATE_CARD = 'LINKCY_API_ERROR_CREATE_CARD';
    public const LINKCY_API_PARTNER_LOGIN_ERROR = 'LINKCY_API_PARTNER_LOGIN_ERROR';
    public const LINKCY_API_ERROR_GET_CARD_INFO = 'LINKCY_API_ERROR_GET_CARD_INFO';

    //    ### Email ###
    public const TRANSPORT_EXCEPTION_ERROR = 'TRANSPORT_EXCEPTION_ERROR';
    public const MAIL_SYNTAX_ERROR = 'MAIL_SYNTAX_ERROR';
    public const MAIL_RUNTIME_ERROR = 'MAIL_RUNTIME_ERROR';
    public const MAIL_LOADER_ERROR = 'MAIL_LOADER_ERROR';

    //    token on login
    public const TOKEN_NOT_FOUND = 'TOKEN_NOT_FOUND';
    public const TOKEN_EXPIRED = 'TOKEN_EXPIRED';
    public const TOO_MANY_VERIFICATION_ATTEMPTS = 'TOO_MANY_VERIFICATION_ATTEMPTS';
    public const USER_NOT_CONNECTED = 'USER_NOT_CONNECTED';
    public const PASSWORD_NOT_CHANGED = 'PASSWORD_NOT_CHANGED';

    public const STEP_INVALID = 'STEP_INVALID';

    public const USER_PASSWORD_NOT_CHANGED = 'USER_PASSWORD_NOT_CHANGED';



}
